In [218]:
import pypsa
import pandas as pd
import numpy as np
import xarray as xr

import matplotlib.pyplot as plt
import seaborn as sns
import re

In [219]:
from _helpers_notebooks import mock_snakemake
snakemake = mock_snakemake(
            "collect_figures",
            scenario="penalty-oc", # penalty-sa, penalty-ea, penalty-nwa, penalty-oc
            sort="test", # TODO update
            demand="False",
    )

In [220]:
scenario = snakemake.wildcards.scenario
mga_scenario = "mga-eur-nwa-2"

### Paths

In [ ]:
trade_model = f"../../results/cost_year~2050/interone~hbi/intertwo~eaf-grid/final~steel/scenario~{scenario}/network.nc"
trade_model_mga = f"../../results/cost_year~2050/interone~hbi/intertwo~eaf-grid/final~steel/scenario~{mga_scenario}/network.nc"

### Read trade model

In [222]:
n = pypsa.Network(trade_model)
n_mga = pypsa.Network(trade_model_mga)

WARNING:pypsa.network.io:Importing network from PyPSA version v0.0.0 while current version is v0.35.0. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.network.io:New version 1.1.2 available! (Current: 0.35.0)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, links, loads
WARNING:pypsa.network.io:Importing network from PyPSA version v0.0.0 while current version is v0.35.0. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.network.io:New version 1.1.2 available! (Current: 0.35.0)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, links, loads

### Get prices

In [223]:
# Steel price analysis
steel_price = n.buses_t.marginal_price.loc[:, n.buses[n.buses.carrier == "steel"].index]
steel_price

Bus,Europe_steel,Far_West_Europe_steel,Middle_East_steel,North_West_Africa_steel,Subsaharan_Africa_steel,North_America_steel,Eurasia_steel,South_America_steel,South_South_America_steel,Central_America_steel,West_Asia_steel,East_Asia_steel,Pacific_Asia_steel,East_East_Asia_steel,Oceania_steel
snapshot,,,,,,,,,,,,,,,
now,681.470691,698.448266,684.455585,670.140798,660.34864,693.413217,699.912531,670.78762,665.533455,714.621799,702.598727,735.03076,699.663304,710.823705,636.035841

In [224]:
# Steel price analysis
steel_price_mga_presolve = n_mga.buses_t.marginal_price.loc[:, n_mga.buses[n_mga.buses.carrier == "steel"].index]
steel_price_mga_presolve

Bus,Europe_steel,Far_West_Europe_steel,Middle_East_steel,North_West_Africa_steel,Subsaharan_Africa_steel,North_America_steel,Eurasia_steel,South_America_steel,South_South_America_steel,Central_America_steel,West_Asia_steel,East_Asia_steel,Pacific_Asia_steel,East_East_Asia_steel,Oceania_steel
snapshot,,,,,,,,,,,,,,,
now,19.586335,19.046576,18.664998,18.274636,18.007605,18.909271,19.086506,18.292274,18.148994,19.487626,19.159758,20.044175,19.98307,19.384052,18.948917

### Resolve MGA model with fixed capacties

In [225]:
# After MGA run, store optimal capacities
mga_capacities = {c: n_mga.df(c)[["p_nom_opt"]].copy() 
                  for c in n_mga.branch_components | n_mga.one_port_components
                  if "p_nom_opt" in n_mga.df(c).columns}

# Fix p_nom to p_nom_opt
for c, df in mga_capacities.items():
    n_mga.df(c)["p_nom"] = df["p_nom_opt"]*1.000000001
    n_mga.df(c)["p_nom_extendable"] = False

In [226]:
solver_name = snakemake.config["solver"]["name"]
options = snakemake.config["solver_options"][snakemake.config["solver"]["options"]]
# Re-solve dispatch only (no investment)
n_mga.optimize(n_mga.snapshots, solver_name=solver_name, solver_options=options)

INFO:linopy.model: Solve problem using Gurobi solver
INFO:linopy.model:Solver options:
 - threads: 4
 - method: 2
 - crossover: 0
 - BarConvTol: 1e-06
 - Seed: 123
 - AggFill: 0
 - PreDual: 0
 - GURO_PAR_BARDENSETHRESH: 200
INFO:linopy.io: Writing time: 0.03s

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2797620

INFO:gurobipy:Set parameter LicenseID to value 2797620

Academic license - for non-commercial use only - expires 2027-03-24

INFO:gurobipy:Academic license - for non-commercial use only - expires 2027-03-24

Read LP format model from file /tmp/linopy-problem-xc9i64pp.lp

INFO:gurobipy:Read LP format model from file /tmp/linopy-problem-xc9i64pp.lp

Reading time = 0.01 seconds

INFO:gurobipy:Reading time = 0.01 seconds

obj: 2175 rows, 1065 columns, 4245 nonzeros

INFO:gurobipy:obj: 2175 rows, 1065 columns, 4245 nonzeros

Set parameter Threads to value 4

INFO:gurobipy:Set parameter Threads to value 4

Set parameter Method to value 2

INFO:gurobipy:Set parameter Method to value 2

Set parameter Crossover to value 0

INFO:gurobipy:Set parameter Crossover to value 0

Set parameter BarConvTol to value 1e-06

INFO:gurobipy:Set parameter BarConvTol to value 1e-06

Set parameter Seed to value 123

INFO:gurobipy:Set parameter Seed to value 123

Set parameter AggFill to value 0

INFO:gurobipy:Set parameter AggFill to value 0

Set parameter PreDual to value 0

INFO:gurobipy:Set parameter PreDual to value 0

Set parameter GURO_PAR_BARDENSETHRESH to value 200

INFO:gurobipy:Set parameter GURO_PAR_BARDENSETHRESH to value 200

Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (linux64 - "Ubuntu 20.04 LTS")

INFO:gurobipy:Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (linux64 - "Ubuntu 20.04 LTS")

INFO:gurobipy:

CPU model: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]

INFO:gurobipy:CPU model: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]

Thread count: 4 physical cores, 8 logical processors, using up to 4 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 4 threads

INFO:gurobipy:

Non-default parameters:

INFO:gurobipy:Non-default parameters:

Method  2

INFO:gurobipy:Method  2

BarConvTol  1e-06

INFO:gurobipy:BarConvTol  1e-06

Crossover  0

INFO:gurobipy:Crossover  0

AggFill  0

INFO:gurobipy:AggFill  0

PreDual  0

INFO:gurobipy:PreDual  0

Seed  123

INFO:gurobipy:Seed  123

Threads  4

INFO:gurobipy:Threads  4

GURO_PAR_BARDENSETHRESH  200

INFO:gurobipy:GURO_PAR_BARDENSETHRESH  200

INFO:gurobipy:

Optimize a model with 2175 rows, 1065 columns and 4245 nonzeros

INFO:gurobipy:Optimize a model with 2175 rows, 1065 columns and 4245 nonzeros

Model fingerprint: 0x8ef047c7

INFO:gurobipy:Model fingerprint: 0x8ef047c7

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [6e-01, 1e+00]

INFO:gurobipy:  Matrix range     [6e-01, 1e+00]

  Objective range  [5e+00, 1e+03]

INFO:gurobipy:  Objective range  [5e+00, 1e+03]

  Bounds range     [0e+00, 0e+00]

INFO:gurobipy:  Bounds range     [0e+00, 0e+00]

  RHS range        [7e-08, 1e+09]

INFO:gurobipy:  RHS range        [7e-08, 1e+09]

Warning: Model contains large rhs

INFO:gurobipy:Warning: Model contains large rhs

         Consider reformulating model or setting NumericFocus parameter

INFO:gurobipy:         Consider reformulating model or setting NumericFocus parameter

         to avoid numerical issues.

INFO:gurobipy:         to avoid numerical issues.

Presolve removed 2153 rows and 611 columns

INFO:gurobipy:Presolve removed 2153 rows and 611 columns

Presolve time: 0.02s

INFO:gurobipy:Presolve time: 0.02s

Presolved: 22 rows, 454 columns, 755 nonzeros

INFO:gurobipy:Presolved: 22 rows, 454 columns, 755 nonzeros

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 1.180e+02

INFO:gurobipy: AA' NZ     : 1.180e+02

 Factor NZ  : 2.030e+02

INFO:gurobipy: Factor NZ  : 2.030e+02

 Factor Ops : 2.295e+03 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 2.295e+03 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.66245991e+13 -3.52878192e+13  5.36e+08 3.64e-12  1.64e+12     0s

INFO:gurobipy:   0   1.66245991e+13 -3.52878192e+13  5.36e+08 3.64e-12  1.64e+12     0s

   1   2.39694961e+12 -1.42171783e+13  4.39e+07 1.90e-11  1.45e+11     0s

INFO:gurobipy:   1   2.39694961e+12 -1.42171783e+13  4.39e+07 1.90e-11  1.45e+11     0s

   2   1.40109722e+12 -8.45822620e+11  7.85e+06 2.39e-11  2.61e+10     0s

INFO:gurobipy:   2   1.40109722e+12 -8.45822620e+11  7.85e+06 2.39e-11  2.61e+10     0s

   3   1.20351735e+12  1.01668250e+12  3.62e+05 8.91e-11  1.33e+09     0s

INFO:gurobipy:   3   1.20351735e+12  1.01668250e+12  3.62e+05 8.91e-11  1.33e+09     0s

   4   1.19413971e+12  1.19371775e+12  1.01e+03 1.55e-10  3.64e+06     0s

INFO:gurobipy:   4   1.19413971e+12  1.19371775e+12  1.01e+03 1.55e-10  3.64e+06     0s

   5   1.19411297e+12  1.19411296e+12  7.68e-02 7.91e-11  2.58e+02     0s

INFO:gurobipy:   5   1.19411297e+12  1.19411296e+12  7.68e-02 7.91e-11  2.58e+02     0s

   6   1.19411297e+12  1.19411297e+12  8.29e-03 5.91e-11  3.13e+01     0s

INFO:gurobipy:   6   1.19411297e+12  1.19411297e+12  8.29e-03 5.91e-11  3.13e+01     0s

   7   1.19411297e+12  1.19411297e+12  6.23e-04 8.69e-11  2.86e+00     0s

INFO:gurobipy:   7   1.19411297e+12  1.19411297e+12  6.23e-04 8.69e-11  2.86e+00     0s

   8   1.19411297e+12  1.19411297e+12  1.97e-05 2.89e-11  3.46e-01     0s

INFO:gurobipy:   8   1.19411297e+12  1.19411297e+12  1.97e-05 2.89e-11  3.46e-01     0s

   9   1.19411297e+12  1.19411297e+12  1.07e-06 1.95e-10  6.05e-02     0s

INFO:gurobipy:   9   1.19411297e+12  1.19411297e+12  1.07e-06 1.95e-10  6.05e-02     0s

  10   1.19411297e+12  1.19411297e+12  5.30e-08 9.08e-11  6.52e-03     0s

INFO:gurobipy:  10   1.19411297e+12  1.19411297e+12  5.30e-08 9.08e-11  6.52e-03     0s

  11   1.19411297e+12  1.19411297e+12  1.49e-07 3.44e-11  1.84e-03     0s

INFO:gurobipy:  11   1.19411297e+12  1.19411297e+12  1.49e-07 3.44e-11  1.84e-03     0s

  12   1.19411297e+12  1.19411297e+12  3.82e-08 7.62e-12  2.30e-04     0s

INFO:gurobipy:  12   1.19411297e+12  1.19411297e+12  3.82e-08 7.62e-12  2.30e-04     0s

  13   1.19411297e+12  1.19411297e+12  1.19e-07 2.73e-12  3.22e-05     0s

INFO:gurobipy:  13   1.19411297e+12  1.19411297e+12  1.19e-07 2.73e-12  3.22e-05     0s

  14   1.19411297e+12  1.19411297e+12  6.22e-08 1.14e-12  3.83e-06     0s

INFO:gurobipy:  14   1.19411297e+12  1.19411297e+12  6.22e-08 1.14e-12  3.83e-06     0s

  15   1.19411297e+12  1.19411297e+12  7.34e-08 9.09e-13  4.35e-07     0s

INFO:gurobipy:  15   1.19411297e+12  1.19411297e+12  7.34e-08 9.09e-13  4.35e-07     0s

INFO:gurobipy:

Barrier solved model in 15 iterations and 0.07 seconds (0.00 work units)

INFO:gurobipy:Barrier solved model in 15 iterations and 0.07 seconds (0.00 work units)

Optimal objective 1.19411297e+12

INFO:gurobipy:Optimal objective 1.19411297e+12

INFO:gurobipy:
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 1065 primals, 2175 duals
Objective: 1.19e+12
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper were not assigned to the network.

('ok', 'optimal')

In [227]:

# Now marginal prices are meaningful again
steel_price_mga = n_mga.buses_t.marginal_price.loc[
    :, n_mga.buses[n.buses.carrier == "steel"].index
]

steel_price_mga

Bus,Europe_steel,Far_West_Europe_steel,Middle_East_steel,North_West_Africa_steel,Subsaharan_Africa_steel,North_America_steel,Eurasia_steel,South_America_steel,South_South_America_steel,Central_America_steel,West_Asia_steel,East_Asia_steel,Pacific_Asia_steel,East_East_Asia_steel,Oceania_steel
snapshot,,,,,,,,,,,,,,,
now,718.233706,698.441459,684.448799,670.13503,651.7044,693.407454,699.905722,670.78344,665.529275,714.615007,702.590919,735.022894,732.78216,710.81588,690.367153

### Price difference

In [228]:
(steel_price_mga - steel_price).round(2)

Bus,Europe_steel,Far_West_Europe_steel,Middle_East_steel,North_West_Africa_steel,Subsaharan_Africa_steel,North_America_steel,Eurasia_steel,South_America_steel,South_South_America_steel,Central_America_steel,West_Asia_steel,East_Asia_steel,Pacific_Asia_steel,East_East_Asia_steel,Oceania_steel
snapshot,,,,,,,,,,,,,,,
now,36.76,-0.01,-0.01,-0.01,-8.64,-0.01,-0.01,-0.0,-0.0,-0.01,-0.01,-0.01,33.12,-0.01,54.33